#q1: this is to set seed. By doing so, the initiation point is always the same, 
# not random.
set.seed(2) 

# assign the value 30 to the variable "sampleSize"
sampleSize <- 30

#q2: randomly generate 20000 numbers that obeyed normal distribution with mean 
# 20 and standard deviation 3. 
# Then assign those numbers to the vector "studentPop".
studentPop <- rnorm(20000,mean=20,sd=3)

#investigate studentPop now. How many rows? What are the values look like? 
# Are they close to the mean value 20?
str(studentPop)
summary(studentPop)

#q3: draw sampleSize (30 sample defined above) from studentPop and 
# assign the 30 numbers to "undergrads".
undergrads <- sample(studentPop,size=sampleSize,replace=TRUE)

#q4: create a sample of graduate students--randomly generate 30 numbers 
# (use sampleSize) that obeyed normal distribution with mean 25 and sd 3. 
# See the mean is 5 years older than the undergraduate sample apparently.  
# Assign the numbers to the vector "grads".
# Sample size is sampleSize (==30), mean is 25, standard deviation is 3. 
grads <- rnorm(sampleSize,mean=25,sd=3)

#q5: Randomly assign either the grads sample or the undergrads sample to 
# testSample, depending on the value generated by runif(1).
# "runif(1)" would generate a random number between 0 and 1. 
# If the number is greater than 0.5, assign grads sample to testSample. 
# Otherwise, assign undergrads sample to testSample.
if (runif(1)>0.5) { testSample <- grads } else { testSample <- undergrads }

#q6: calculate the mean of "testSample" What is the mean of testSample?
mean(testSample)


#q7: Generate 100 sample means from studentPop and assign it as mySample
mySample <- replicate(100, mean(sample(studentPop, sampleSize, replace = TRUE)),
                      simplify = TRUE)

#q8: Compare mean(testSample) to that list of sample means (mySample) 
# and see where it falls. quantile() function helps display data distribution. 
# Produce quantiles on thresholds 2.5% and 97.5%.
quantile(mySample, c(0.025, 0.975))
if(round(mean(testSample)) == 25){
  print("Grads")
} else {
  print("Undergrads")
}
  
#q9: if the sample mean is less than quantiles on thresholds 2.5% or greater 
# than quantiles on thresholds 97.5%, then it can be definded as extreme. 
# Otherwise it is not extreme.
if (mean(testSample) < quantile(mySample, probs=0.025) | 
    mean(testSample) > quantile(mySample, probs=0.975))
{ print("Sample mean is extreme") } else { print("Sample mean is not extreme") }
